#!/bin/bash

function pall(){
  post_dir=$1
  gen_dir=$2
  index=$3
  title=$4

  rm -f "$index.md"
  rm -f "$index.xml"
  rm -f "$index.html"

  echo $post_dir
  mkdir -p $gen_dir

  echo "<rss version='2.0'>
  <channel>
    <title>Mars的笔记</title>
    <link>http://marsishandsome.github.io/</link>
    <description>by Mars</description>
  " > "$index.xml"

  pFolder

  echo "  </channel>
</rss>
  ">> "$index.xml"

  ./pmd "$index.md" > "$index.html"
}

function pFolder(){
  for post in `ls $post_dir`
  do
    if [ -d "$post_dir/$post" ]; then
      echo "  $post"
      pSubFolder "$post_dir/$post" $post
    fi
  done
}

function pSubFolder(){
  sub_post_dir=$1
  category=$2

  echo -e "\n### $category" >> "$index.md"

  for post in `ls $sub_post_dir`
  do
    if [ -f "$sub_post_dir/$post" ]; then
      post_without_md=${post%.md}
      post_with_space=${post_without_md//_/ }
      echo "    $post_with_space"

      ./pmd "$sub_post_dir/$post" > "$gen_dir/$post_without_md.html"
      echo -e "- [$post_with_space]($gen_dir/$post_without_md.html)" >> "$index.md"
      echo "
      <item>
        <title>$post_with_space</title>
        <link>http://marsishandsome.github.io/$gen_dir/$post_without_md.html</link>
        <description>$post_with_space</description>
      </item>
      " >> "$index.xml"
    fi
  done
}

rm -rf gen
pall "posts" "gen" "index" "Mars的笔记"
pall "drafts" "gen" "drafts" "Mars的草稿"
