#!/bin/bash

function pall(){
  post_dir=$1
  gen_dir=$2
  index=$3
  title=$4

  mkdir -p $gen_dir
  echo "#$title" > "$index.md"
  echo "
<rss version='2.0'>
  <channel>
    <title>Mars的笔记</title>
    <link>http://marsishandsome.github.io/</link>
    <description>by Mars</description>
  " > "$index.xml"

  pfolder $post_dir $gen_dir $index "Common"

  echo "
  </channel>
</rss>
  ">> "$index.xml"

  ./pmd "$index.md" > "$index.html"
}

function pfolder(){
  post_dir=$1
  gen_dir=$2
  index=$3
  category=$4

  echo -e "\n### $category" >> "$index.md"

  for post in `ls $post_dir`
  do 
    if [ -d "$post_dir/$post" ]; then
      pfolder "$post_dir/$post" $gen_dir $index $post
    else
      post_without_md=${post%.md}
      post_with_space=${post_without_md//_/ }
      echo $post_with_space

      ./pmd "$post_dir/$post" > "$gen_dir/$post_without_md.html"
      echo -e "- [$post_with_space]($gen_dir/$post_without_md.html)" >> "$index.md"
      echo "
      <item>
        <title>$post_with_space</title>
        <link>http://marsishandsome.github.io/$gen_dir/$post_without_md.html</link>
        <description>$post_with_space</description>
      </item>
      " >> "$index.xml"
    fi
  done
}

rm -rf gen
pall "posts" "gen" "index" "Mars的笔记"
pall "drafts" "gen" "drafts" "Mars的草稿"

